apiVersion: v1
kind: Secret
metadata:
  name: logforwarder-db-credentials
  namespace: logforwarder
  labels:
    app: logforwarder-middleware
type: Opaque
stringData:
  url: "jdbc:clickhouse://clickhouse.logforwarder.svc.cluster.local:8123/logforwarder"
  username: "logforwarder"
  password: "CHANGE_ME_PRODUCTION_PASSWORD"

---
apiVersion: v1
kind: Secret
metadata:
  name: logforwarder-elasticsearch-credentials
  namespace: logforwarder
  labels:
    app: logforwarder-middleware
type: Opaque
stringData:
  username: "elastic"
  password: "CHANGE_ME_PRODUCTION_PASSWORD"

---
apiVersion: v1
kind: Secret
metadata:
  name: logforwarder-redis-credentials
  namespace: logforwarder
  labels:
    app: logforwarder-middleware
type: Opaque
stringData:
  password: "CHANGE_ME_PRODUCTION_PASSWORD"

---
apiVersion: v1
kind: Secret
metadata:
  name: logforwarder-app-secrets
  namespace: logforwarder
  labels:
    app: logforwarder-middleware
type: Opaque
stringData:
  jwt-secret: "CHANGE_ME_PRODUCTION_JWT_SECRET_AT_LEAST_32_CHARACTERS_LONG"

---
apiVersion: v1
kind: Secret
metadata:
  name: logforwarder-docker-registry
  namespace: logforwarder
  labels:
    app: logforwarder-middleware
type: kubernetes.io/dockercfg
data:
  .dockercfg: eyJhdXRocyI6e319Cg==

---
apiVersion: v1
kind: Secret
metadata:
  name: logforwarder-tls
  namespace: logforwarder
  labels:
    app: logforwarder-middleware
type: kubernetes.io/tls
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJrVENDQVRlZ0F3SUJBZ0lCQVRBTkJna3Foa2lHOXcwQkFRc0ZBREFsTXFzR0NSRDJZM0oxQzhKaWEybGsKQ2pCR01Rc3dDUVlEVlFRR0V3SlZVekVpTUNBR0ExVUVDQk1aUjI5dloyNWxSMjl2WjJ4bElGTjBkWFJsTVFJeApCZ05WQkFNVEkzTmxjblpsY2kxelpVQXhDakJHVzJsdGNrOVROMEZCUVZWUQvWnRCVkpVS1pVbkpUVXpVMlkwMjEKNlFUVkJSVkJRVVRWVFVUVkJCT24K
  tls.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUJPd0lCQURBTkJna3Foa2lHOXcwQkFRRUZBQXNDQURRQkhtdFNzaW5NRHBQVjI1cFlVdDRaMDlYVW1oWApXR3R3WTBkSGJHMUVSVEJQUlRWQk16QTJSVEkzVlRNd01ESTBUMEZCUVRWUGSRYU5FbE5UVEJoVjB0Wk1WbEkKQ2pCR1czaHdTVU5QT1ZCSE1qVk5NRUZDUWPOV1pWZHhhR0Z1Vkhka1EzQmhialpSWVVOSGEyaDNNMkZ5YmpOVApWRUl5VTBSVk9FNVFNMG9yV1d4d2JHbDVhR3RyVDBGSE5XMDZMV05uUTBSbGIySmxaMlpsY2tGd1F6Qlkya04zCllrOVhVbXRqTUUxVllrRmhkMGx1VWpCVk1rMDJVMGQzYkZCVFNqQk9la0U1VFcxNFlVNXNiR0ZUVGpCRQpVMVZvVDFSbk9FMXNWelY0TlhFM05EWlRWRXRHTWpB...
