apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "logforwarder.fullname" . }}
  labels:
    {{- include "logforwarder.labels" . | nindent 4 }}
data:
  elasticsearch-uri: {{ .Values.config.elasticsearch.uri }}
  redis-host: {{ .Values.config.redis.host }}
  redis-port: {{ .Values.config.redis.port | quote }}
  kafka-bootstrap-servers: {{ .Values.config.kafka.bootstrapServers }}
  websocket-origins: {{ .Values.config.websocket.allowedOrigins }}
