apiVersion: v1
kind: Secret
metadata:
  name: {{ include "logforwarder.fullname" . }}-db
  labels:
    {{- include "logforwarder.labels" . | nindent 4 }}
type: Opaque
stringData:
  url: {{ .Values.secrets.database.url }}
  username: {{ .Values.secrets.database.username }}
  password: {{ .Values.secrets.database.password }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "logforwarder.fullname" . }}-elasticsearch
  labels:
    {{- include "logforwarder.labels" . | nindent 4 }}
type: Opaque
stringData:
  password: {{ .Values.secrets.elasticsearch.password }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "logforwarder.fullname" . }}-redis
  labels:
    {{- include "logforwarder.labels" . | nindent 4 }}
type: Opaque
stringData:
  password: {{ .Values.secrets.redis.password }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "logforwarder.fullname" . }}-jwt
  labels:
    {{- include "logforwarder.labels" . | nindent 4 }}
type: Opaque
stringData:
  secret: {{ .Values.secrets.jwt.secret }}
